module.exports = [ { name: 'Fantastic Plastic Keyboard',
    description: 'aliquid enim quis',
    price: '203.00',
    color: 'cyan',
    category: 'Books',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Small Cotton Pizza',
    description: 'magni exercitationem eum',
    price: '877.00',
    color: 'lavender',
    category: 'Games',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Licensed Granite Chips',
    description: 'maxime et id',
    price: '515.00',
    color: 'white',
    category: 'Sports',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Rustic Metal Salad',
    description: 'minima vel veniam',
    price: '51.00',
    color: 'orange',
    category: 'Industrial',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Handmade Steel Shoes',
    description: 'qui omnis eum',
    price: '365.00',
    color: 'pink',
    category: 'Shoes',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Intelligent Frozen Ball',
    description: 'et dolores molestias',
    price: '568.00',
    color: 'salmon',
    category: 'Books',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Rustic Frozen Chair',
    description: 'non et et',
    price: '702.00',
    color: 'lavender',
    category: 'Industrial',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Handcrafted Steel Chicken',
    description: 'maxime soluta veniam',
    price: '632.00',
    color: 'yellow',
    category: 'Computers',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Handcrafted Soft Keyboard',
    description: 'qui voluptatibus soluta',
    price: '108.00',
    color: 'white',
    category: 'Kids',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Fantastic Wooden Pizza',
    description: 'hic facilis eos',
    price: '651.00',
    color: 'teal',
    category: 'Electronics',
    image: 'http://lorempixel.com/640/480/fashion' },
  { name: 'Ergonomic Plastic Shoes',
    description: 'accusantium ut dolor',
    price: '431.00',
    color: 'red',
    category: 'Clothing',
    image: 'http://lorempixel.com/640/480/fashion' } ]